### PR TITLE
[MP-6984] docs: documents website landing page

### PR DESCRIPTION
**Pull request by shravan-balasubramanian**
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] My commits have standard messages as mentioned in [Contributing Guidelines](./../CONTRIBUTING.md)

### CODE REVIEW

**Comment by shravan-balasubramanian** [comment]
Screenshot 2020-05-27 at 7 31 11 PM

Let me know any improvements, enhancements
I might need suggestions 
* Whether to keep navbar fixed or sticky @asifahmedfw

**Comment by asifahmedfw** [comment]
> Screenshot 2020-05-27 at 7 31 11 PM
> 
> Let me know any improvements, enhancements
> I might need suggestions
> 
> * Whether to keep navbar fixed or sticky @asifahmedfw
>   TODO
> * Add footer, dialogue box and products dropdown in the header

Keep it fixed. Also We selected the background with icons right?

**Comment by shravan-balasubramanian** [comment]
> > Screenshot 2020-05-27 at 7 31 11 PM
> > Let me know any improvements, enhancements
> > I might need suggestions
> > 
> > * Whether to keep navbar fixed or sticky @asifahmedfw
> >   TODO
> > * Add footer, dialogue box and products dropdown in the header
> 
> Keep it fixed. Also We selected the background with icons right?

Pavan said we selected the bg with color and not icons

**Comment by asifahmedfw** [comment]
@shravan-balasubramanian hey, ideally all commits should be a 'docs' change. A feat bumps up the version. And its not a feature in the product itself. Please raise a new PR with changed messages if possible.

**Comment by shravan-balasubramanian** [comment]
Closing this since the commit messages are different

**Pull request closed without merging**
